### ISSUE TITLE
Freshly built alpaca errors  (web-edit:view:web-edit:form failed to execute)

### ISSUE THREAD

**Issue by wmodes** [gitana/alpaca#212]
At this point I've tried nearly every combination of Alpaca versions, options, views, configurations I can think of. The only one I've gotten working has been a package based on 1.1.2 built for meteor.

I just built a fresh version of alpaca from github according to the github instructions. It built fine and generated bootstrap, jqueryui, and web versions. I included the bootstrap version into my page with js to build one of the sample schemas from the tutorial at http://www.alpacajs.org/tutorial.html. I've included all the dependencies. 

However, when I go to the page, nothing renders and the console reports:

    {"message":"The compiled template: web-edit:view:web-edit:form failed to execute: undefined is not a function"}

What information would be useful to help get me on my feet and get this working?

By the way, the other problem I've run into (the reason I'm not working with the 1.1.2 meteor package) was a failure to find the getValue function attached to the Submit keypress, something I've read in other reported issues.

**Comment by arthurportas** [comment]
Hi,

something is missing in your app...please provide a public codepen or jsfiddle for us to help. If you keep having trouble let us know.

Cheers,

**Comment by wmodes** [comment]
I was running into too many errors integrating with meteor and on a compressed timeline. So I went with jdorn's json-editor. I'll close this out so it isn't an open issue.
